### ISSUE TITLE
Support for Pytractor

### ISSUE THREAD

**Issue by dfdf-santosh** [kpodl/pytractor#15]
Hi,

We have built our test suite in Selenium WebDriver. Now our development team is migrating from JQuery, JavaScript to AngularJS. So we are thinking to migrate our WebDriver script as well.

I am new to selenium PYtractor and PROtractor.
I would like to know how would i get the support for both and which is best suited?.

**Can we get all the features and api's in PYtractor that are provided by selenium PROtractor?

I know and worked on python unittest framework.
I could not decide which one to prefer either PYtractor or PROtractor.

When we can expect stable version of PYtractor and full support ?
What would be the next release of PYtractor and what all the new features will be included in it?

**Comment by kpodl** [comment]
Pytractor was created because I wanted to use Python for end-to-end testing. If you are comfortable using JavaScript, then protractor would probably be the way to go. Personally, I would use robotframework  and [Extended Selenium Library](https://github.com/rickypc/robotframework-extendedselenium2library).

As for stable releases, features, or support, I cannot make any predictions or guarantees. This is a project I am working on in my free time.
